### ISSUE TITLE
Room background/ads furni height is wrong

### ISSUE THREAD

**Issue by victoriaellenx** [SageSaga/habgen-error-gits#13]
When you place a room ad down in a room, the height is 1 when you walk on it. 
We did edititem command on the room ad a while ago and it showed that the height was at 0 but it never saved.

**Comment by SageSaga** [comment]
![room](https://github.com/SageSaga/habgen-error-gits/assets/77630878/0f304b84-de19-40f7-aa9b-c18ac23d588d)

Picture shows value for allow_walk = 0 but doesn't happen in game.

**Comment by dev-mello** [comment]
Fixed. Height is now 0.
