### ISSUE TITLE
GOTW leaderboard

### ISSUE THREAD

**Issue by victoriaellenx** [SageSaga/habgen-error-gits#19]
When you do :gotw command the points goes to the gotw points which are shown on the users screen but not to the leaderboard which are on the website

**Comment by dev-mello** [comment]
It updates after they log out or reload client

**Comment by dev-mello** [comment]
Fixed. Currency ID was set to 104 but 103 is used by the command.

Files changed:
- app\Http\Controllers\GotwController.php

**Comment by dev-mello** [comment]
Added ability to reset GOTW points via Housekeeping button.

Settings added:
- reset_gotw_discordhook (URL of Discord webhook for notifications)

Permissions added:
- reset_gotw

Files changed:
- database\seeders\HousekeepingPermissionSeeder.php (Added perm reset_gotw)
- resources\views\users\index.blade.php (Added reset GOTW button)
- routes\web.php (Added /users/reset_gotw)
- app\Http\Controllers\UserController.php (Added resetGotw function)
- app\Models\UserCurrency.php (Fixed user() bit)
- resources\views\users\reset-gotw.blade.php (Created view for it)
