### ISSUE TITLE
40% issue.

### ISSUE THREAD

**Issue by zerohab** [SageSaga/habgen-error-gits#29]
A couple users complaining they're stuck on 40% after trying to clear cache and cookies, trying different browsers.

**Comment by MiroVerleysen** [comment]
Did you ask for a developer tools -> console screenshot?

**Comment by zerohab** [comment]
I have a couple screenshots. I've asked for developer tools screenshots, bare with.

**Comment by zerohab** [comment]
Fixed. It was an issue on the users end, not ours.
