### ISSUE TITLE
Broken Commands

### ISSUE THREAD

**Issue by zerohab** [SageSaga/habgen-error-gits#3]
:commands
:endevent(s)
:youtube commands, theres a couple.

**Comment by SageSaga** [comment]
What do you mean by :endevent (s) ? what does the S mean?

Youtube command can't be done right now when the websocket is already so ass at the moment with logins that I definitely say that the youtube shouldn't be in

**Comment by zerohab** [comment]
;endsevents & ;endevent aint working.

**Comment by SageSaga** [comment]
:endevent is working, :commands is a HTML issue, youtube commands not recommended at this time.
