### ISSUE TITLE
VIP cycles.

### ISSUE THREAD

**Issue by zerohab** [SageSaga/habgen-error-gits#31]
User sk who has GVIP on his main and two alts is stating that he is not getting the three diamond per fifteen minutes alongside the credits and duckets. Is there anyway this can be checked?

**Comment by MiroVerleysen** [comment]
Checking rn

**Comment by MiroVerleysen** [comment]
Set auto_points amount like this:
![image](https://github.com/SageSaga/habgen-error-gits/assets/55786561/8ab384d3-becd-41ca-b8cb-38931958c1e2)

Not working for now tho, wrong column, emu reboot needed?

**Comment by zerohab** [comment]
I did one by accident last night after you posted this. It should hopefully fix it now unless you have any other issues?
