### ISSUE TITLE
Some bugs

### ISSUE THREAD

**Issue by zerohab** [SageSaga/habgen-error-gits#4]
User MilkeTea reported in the #bugs section that the Wired - EFFECT: COLLISON ON NEXT TO FURNITURE that the wired forgets everything in the room. He also said that when he relogs from the nitro-client that his thumbnails are missing or gone, double log-out/login notifications.

**Comment by SageSaga** [comment]
Only log in and out notifications will be fixed, the others are issues unheard of before
